### PR TITLE
Add Chinese support

### PR DESCRIPTION
**Pull request by SteveNotSet**
I have translated all the text of this mod based on the original Chinese text of Genshin Impact (原神).

### CODE REVIEW

**Comment by SteveNotSet** [comment]
Notice
1. Hoyoverse is translated to 米哈游(miHoYo)，as Chinese version of Genshin Impact is still published by miHoYo, not Hoyoverse.
2. sol is modified to so. The original text in Genshin Impact is so, not sol.
屏幕截图 2024-01-17 010633
3. Don is modified to don (lower case), and Ka is modified to ka.
4. The four items' names are from the original text. “genshinstrument.advancements.main.windsong_lyre.title” and “genshinstrument.advancements.main.vintage_lyre.title” are from Genshin Impact's advancements' names.
5. The disclaimer is not a full translation of your original text. I copied some of Genshin Impact's disclaimer. But my translation expresses the same meaning as your original text.
屏幕截图 2024-01-17 010633

**Comment by StavWasPlayZ** [comment]
Xiexie! 😊  
Will shortly review & merge the PR.

> sol is modified to so. The original text in Genshin Impact is so, not sol.

> Don is modified to don (lower case), and Ka is modified to ka.

Will fix on the English translations as well - my bad, and thanks for pointing it out!

Regarding any other decision-makings behind translations on that behalf - I 100% trust your judgement.  
I'd also highly appreciate it if you could point out any other issues with my original English translations, if more are present. 🙂

Once again, thank you so, *so* much for your time and effort in localization. It's truly not taken for granted <3.   
Cheers!

**Comment by SteveNotSet** [comment]
> As I have changed the base branch to the dev channel, it appears translation files for Chinese are already present following issue #11. Could you kindly review [the current translations](https://github.com/StavWasPlayZ/Genshin-Instruments/blob/aa78e8ca330fa2a31e7eafdc86fc9dfbe1353a02/src/main/resources/assets/genshinstrument/lang/zh_cn.json) against the present one?

I found that version just after I complete my own translation. That one seems like partly machine-translated text. My version is translated independently, and it is completely different.

I have updated my fork, fixing some mistakes and merging some of the present tranlations.

**Review by StavWasPlayZ — APPROVED** [review]
Seems valid enough for me

**Comment by StavWasPlayZ** [comment]
Thanks again for your contributions!

**Pull request merged**
